[package]
name = "fyrox-lite-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox-lite-model = {workspace = true}
syn = {workspace = true}
quote = {workspace = true}
proc-macro2 = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
