[package]
name = "fyrox-lite-cs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fyrox = { workspace = true, default-features = true }
fyrox-lite-cs-lib = { workspace = true, default-features = true }
