[package]
name = "fyrox-lite-lua-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox-lite-api = {path = "../fyrox-lite-api"}
fyrox = {workspace = true}
mlua = { version = "0.9.1", features = ["luau"] }
send_wrapper = "0.6.0"