[package]
name = "fyrox-lite"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
extend = "1.2.0"
lite-macro = { path = "../lite-macro" }
convert_case = {workspace = true}
error = {workspace = true}

[features]
default = ["fyrox/default"]
engine-dylib = ["fyrox/dylib"]