[package]
name = "lite-macro-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {workspace = true}
quote = {workspace = true}
proc-macro2 = {workspace = true}
lite-parser = {path = "../lite-parser"}
lite-model = {path = "../lite-model"}
uuid = {workspace = true}