[package]
name = "fyrox-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fyrox = { workspace = true, features = ["dylib"], default-features = false }
fyrox-c-lib = { workspace = true }
